name: gnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch==2.2.2
    - torch-geometric==2.7.0
    - numpy==1.26.4
    - pandas
    - pandapower
    - matplotlib
    - scikit-learn
    - scipy
    - openpyxl
    - ipykernel
    - ipywidgets
    - tqdm
